---
sidebar: sidebar 
permalink: concept-deploy-netapp-console-local.html 
keywords: deploy, install, vCenter, Linux, high availability, deployment options, netapp console local 
summary: Scopri le opzioni di distribuzione per la distribuzione locale di NetApp Console, incluse le installazioni su vCenter e Linux. 
---
= Opzioni di distribuzione per la distribuzione locale di NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installa la distribuzione locale di NetApp Console nel tuo ambiente vCenter.



[[install-in-your-vcenter-environment]]
=== Installa nel tuo ambiente vCenter

Distribuisci la NetApp Console locale come appliance virtuale nel tuo ambiente vCenter VMware utilizzando un'immagine OVA preconfigurata.

link:task-install-agent-on-prem-ova.html["Installa la distribuzione locale di NetApp Console nel tuo ambiente vCenter"].



[[next-steps]]
== Prossimi passi

Dopo l'implementazione, completa le seguenti attività per iniziare:

* link:task-add-systems.html["Aggiungi i sistemi storage alla distribuzione locale di NetApp Console"]
* link:task-iam-manage-members-permissions.html["Aggiungi membri e assegna ruoli nella distribuzione locale di NetApp Console"]

