---
sidebar: sidebar 
permalink: task-get-help.html 
keywords: help, ticket, open support case, support, netapp support, technical support, call support, phone number, open ticket, web ticket, open an issue 
summary: 'NetApp offre supporto per la distribuzione locale della NetApp Console in diversi modi. Sono disponibili numerose opzioni di auto-supporto gratuite 24x7, come articoli della knowledge base (KB) e un forum della community. La registrazione al supporto include supporto tecnico remoto tramite ticket web.' 
---
= Ottieni assistenza con la distribuzione locale della NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp fornisce supporto per la distribuzione locale di NetApp Console in diversi modi. Sono disponibili numerose opzioni di auto-supporto gratuite 24x7, come articoli della Knowledge Base (KB) e un forum della community. Puoi registrarti per il supporto con il numero di serie di qualsiasi risorsa storage associata alla distribuzione locale di NetApp Console. La registrazione include il supporto tecnico remoto tramite ticket web.



[[use-self-support-options]]
== Usa le opzioni di self-support

Queste opzioni sono disponibili gratuitamente, 24 ore su 24, 7 giorni su 7:

* Documentazione
+
La documentazione relativa alla distribuzione locale della NetApp Console che stai visualizzando.

* https://kb.netapp.com/Cloud/BlueXP["Knowledge base"^]
+
Cerca nella NetApp Knowledge Base gli articoli che ti aiutano a risolvere i problemi.





[[open-a-support-case-with-netapp-console-local-deployment]]
== Apri un caso di supporto con NetApp Console distribuzione locale

Apri una richiesta di supporto utilizzando uno dei numeri di serie del sistema storage NetApp gestiti tramite l'ambiente di distribuzione locale della tua NetApp Console.

.Passaggi
. Vai su  https://mysupport.netapp.com["Sito di supporto NetApp"^] e accedi con le tue credenziali di supporto NetApp.
. Seleziona *Cases and Parts > Create Technical Case*.
. Inserisci il numero di serie del sistema storage NetApp associato al prodotto di distribuzione locale della NetApp Console che presenta il problema.
. Crea un nuovo caso e seleziona il codice di categoria appropriato per la distribuzione locale di NetApp Console.




[[download-a-support-bundle]]
== Scarica un bundle di supporto

Il pacchetto di supporto include i log più recenti e le informazioni di configurazione. Puoi scaricare il pacchetto più recente e inviarlo al supporto tecnico di NetApp se richiesto.

.Passaggi
. Seleziona *Amministrazione > Supporto* per visualizzare la pagina di supporto.
. Nella scheda Support, seleziona *Crea* per creare un pacchetto di log e dati di configurazione.
. Una volta creato il pacchetto, seleziona *Scarica*. Ti viene chiesto di scaricare un file ZIP.
+
Il sistema conserva un solo pacchetto alla volta. La creazione di un nuovo pacchetto di supporto sostituisce quello precedente.


