---
sidebar: sidebar 
permalink: task-console-local-vm-config.html 
keywords: Console local VM, vcenter, esxi, increase cpu, increase ram, vm maintenance, Console local maintenance, Console local operating system, Console local host 
summary: 'Dopo che hai distribuito la Console local deployment, puoi apportare modifiche al tuo host VCenter o ESXi esistente. Ad esempio, puoi aumentare la CPU o la RAM dell"istanza di macchina virtuale che ospita la Console local deployment.' 
---
= Gestisci il tuo vCenter o host ESXi per la distribuzione locale della NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nella NetApp Console distribuzione locale, puoi apportare modifiche al tuo VCenter o host ESXi esistente dopo aver distribuito la Console distribuzione locale. Ad esempio, puoi aumentare la CPU o la RAM dell'istanza di macchina virtuale che ospita la Console distribuzione locale.

Esegui queste attività di manutenzione utilizzando la console web della macchina virtuale:

* Aumenta la dimensione del disco
* Riavvia la distribuzione locale della Console
* Aggiorna le rotte statiche
* Aggiorna i domini di ricerca


.Limitazioni
È possibile solo visualizzare (non aggiornare) le informazioni relative all'indirizzo IP, al DNS e ai gateway tramite la console di manutenzione.



[[access-the-vm-maintenance-console]]
== Accedi alla console di manutenzione della macchina virtuale

Puoi accedere alla console di manutenzione dal client VSphere.

.Passaggi
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Seleziona *Avvia console Web*.
. Accedi all'istanza di macchina virtuale utilizzando il nome utente e la password che hai specificato quando hai creato l'istanza di macchina virtuale. Il nome utente è  `maint` e la password è quella che hai specificato quando hai creato l'istanza di macchina virtuale.




[[change-the-maint-user-password]]
=== Modifica la password dell'utente maint

Puoi cambiare la password per l’utente  `maint`.

.Passaggi
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Seleziona *Avvia console Web*.
. Accedi all'istanza di macchina virtuale utilizzando il nome utente e la password che hai specificato quando hai creato l'istanza di macchina virtuale. Il nome utente è  `maint` e la password è quella che hai specificato quando hai creato l'istanza di macchina virtuale.
. Premi  `1`Invio per visualizzare il  `System Configuration`menu.
. Inserisci  `1` per cambiare la password dell'utente di manutenzione e segui le istruzioni visualizzate sullo schermo.




[[increase-the-cpu-or-ram-of-the-vm-instance]]
=== Aumenta la CPU o la RAM dell'istanza di macchine virtuali

Puoi aumentare la CPU o la RAM dell'istanza di macchina virtuale che ospita la distribuzione locale della Console.

Modifica le impostazioni dell'istanza di macchina virtuale nel tuo VCenter o host ESXi, quindi usa la Console di manutenzione per applicare le modifiche.

.Passaggi nel client VSphere
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Fai clic con il pulsante destro del mouse sull'istanza di macchina virtuale e seleziona *Modifica impostazioni*.
. Aumenta lo spazio su disco rigido utilizzato per /opt o per la partizione /var.
+
.. Seleziona *Hard Disk 2* per aumentare lo spazio del disco rigido utilizzato per /opt.
.. Seleziona *Hard Disk 3* per aumentare lo spazio su disco rigido utilizzato per /var.


. Salva le modifiche.


.Passaggi nella console di manutenzione
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Seleziona *Avvia console Web*.
. Accedi all'istanza di macchina virtuale utilizzando il nome utente e la password che hai specificato quando hai creato l'istanza di macchina virtuale. Il nome utente è  `maint` e la password è quella che hai specificato quando hai creato l'istanza di macchina virtuale.
. Accedi al  `1 to view the `System Configuration` menu.
. Accedi  `2` e segui le istruzioni visualizzate sullo schermo. La console esegue una scansione per rilevare nuove impostazioni e aumenta le dimensioni delle partizioni.




[[view-network-settings-for-the-console-local-deployment-vm]]
=== Visualizza le impostazioni di rete per la VM di distribuzione locale della Console

Visualizza le impostazioni di rete della VM di distribuzione locale della Console nel client vSphere per verificare o risolvere eventuali problemi di rete. Puoi solo visualizzare (non modificare) le seguenti impostazioni di rete: indirizzo IP e dettagli DNS.

.Passaggi
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Seleziona *Avvia console Web*.
. Accedi all'istanza di macchina virtuale utilizzando il nome utente e la password che hai specificato quando hai creato l'istanza di macchina virtuale. Il nome utente è  `maint` e la password è quella che hai specificato quando hai creato l'istanza di macchina virtuale.
. Premi Invio `2` per visualizzare il `Network Configuration` menu.
. Inserisci un numero compreso tra 1 e 6 per visualizzare le impostazioni di rete corrispondenti.




[[update-the-static-routes-for-the-console-local-deployment-vm]]
=== Aggiorna le route statiche per la VM di distribuzione locale della Console

Aggiungi, aggiorna o rimuovi percorsi statici per la VM di distribuzione locale della Console, a seconda delle necessità.

.Passaggi
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Seleziona *Avvia console Web*.
. Accedi all'istanza di macchina virtuale utilizzando il nome utente e la password che hai specificato quando hai creato l'istanza di macchina virtuale. Il nome utente è  `maint` e la password è quella che hai specificato quando hai creato l'istanza di macchina virtuale.
. Premi Invio `2` per visualizzare il `Network Configuration` menu.
. Inserisci  `7` per aggiornare i percorsi statici e segui le istruzioni visualizzate sullo schermo.
. Premi Invio.
. Facoltativamente, puoi apportare ulteriori modifiche.
. Premi  `9` Invio per confermare le modifiche.




[[update-domain-search-settings-for-the-console-local-deployment-vm]]
=== Aggiorna le impostazioni di ricerca del dominio per la VM di distribuzione locale della Console

Puoi aggiornare le impostazioni del dominio di ricerca per la VM di distribuzione locale della Console.

.Passaggi
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Seleziona *Avvia console Web*.
. Accedi all'istanza di macchina virtuale utilizzando il nome utente e la password che hai specificato quando hai creato l'istanza di macchina virtuale. Il nome utente è  `maint` e la password è quella che hai specificato quando hai creato l'istanza di macchina virtuale.
. Premi  `2``Invio per visualizzare il `Network Configuration` menu.
. Inserisci  `8` per aggiornare le impostazioni di ricerca del dominio e segui le istruzioni visualizzate sullo schermo.
. Premi Invio.
. Facoltativamente, puoi apportare ulteriori modifiche.
. Premi  `9` Invio per confermare le modifiche.




[[access-the-console-local-deployment-diagnostic-tools]]
[[connect-vcenter-host]]
=== Accedi agli strumenti di diagnostica della distribuzione locale della Console

Accedi agli strumenti di diagnostica per risolvere i problemi relativi alla distribuzione locale della Console. NetApp Support potrebbe chiederti di farlo durante la risoluzione dei problemi.

.Passaggi
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Seleziona *Avvia console Web*.
. Accedi all'istanza di macchina virtuale utilizzando il nome utente e la password che hai specificato quando hai creato l'istanza di macchina virtuale. Il nome utente è  `maint` e la password è quella che hai specificato quando hai creato l'istanza di macchina virtuale.
. Premi Invio `3` per visualizzare il menu Supporto e diagnostica.
. Premi  `1` per accedere agli strumenti di diagnostica e segui le istruzioni visualizzate sullo schermo.




[[access-the-console-local-deployment-diagnostic-tools-remotely]]
=== Accedi da remoto agli strumenti di diagnostica della distribuzione locale della Console

Puoi accedere agli strumenti di diagnostica da remoto con un programma come Putty. Abilita l'accesso SSH alla VM di distribuzione locale della Console assegnando una password monouso.

L'accesso SSH abilita funzionalità avanzate del terminale come copia e incolla.

.Passaggi
. Apri il client vSphere ed effettua l'accesso al tuo vCenter.
. Seleziona l'istanza di macchina virtuale che ospita la distribuzione locale della Console.
. Seleziona *Avvia console Web*.
. Accedi all'istanza di macchina virtuale utilizzando il nome utente e la password che hai specificato quando hai creato l'istanza di macchina virtuale. Il nome utente è  `maint` e la password è quella che hai specificato quando hai creato l'istanza di macchina virtuale.
. Premi Invio `3` per visualizzare il `Support and Diagnostics` menu.
. Inserisci  `2` per accedere agli strumenti di diagnostica e segui le istruzioni visualizzate sullo schermo per configurare una password monouso che scade dopo 24 ore.
. Utilizza uno strumento SSH come Putty per connetterti alla VM di distribuzione locale della Console utilizzando il nome utente `diag` e la password monouso che hai configurato.

