---
sidebar: sidebar 
permalink: task-audit-console-activity.html 
keywords: administer, monitor, timeline, notifications, alerts, events, notification center, email, audit page, audit action 
summary: 'Dalla pagina Audit puoi controllare l"attività degli utenti (avviata sia dall"interfaccia utente che dalle API) e monitorare lo stato delle operazioni eseguite dalla Console per vedere se ci sono problemi che devi risolvere. Puoi visualizzare lo stato dalla pagina Audit oppure configurare i log di audit perché vengano inviati al tuo server syslog.' 
---
= Verifica l'attività di distribuzione locale della NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dalla pagina Audit puoi controllare l'attività degli utenti avviata sia dall'interfaccia utente che dalle API e puoi monitorare lo stato delle operazioni nella distribuzione locale di NetApp Console e l'utente che le ha avviate.

.Ruoli richiesti
Super amministratore, amministratore dell'organizzazione, amministratore di cartelle e flotte, analista del supporto operativo, super visualizzatore, visualizzatore dell'organizzazione o visualizzatore di cartelle e flotte. link:reference-iam-predefined-roles.html["Scopri i ruoli di accesso"].

Puoi visualizzare l'attività di audit nella distribuzione locale della Console, scaricare un file CSV dei log di audit oppure configurare l'invio dei log di audit al tuo server syslog tramite un webhook.



[[audit-user-activity-from-the-audit-page]]
== Verifica l'attività degli utenti dalla pagina Audit

Usa la pagina Audit per identificare chi ha eseguito un'azione o il suo stato.

La pagina Audit mostra le azioni completate dagli utenti all'interno della tua organizzazione. Ad esempio, puoi verificare chi ha aggiunto un membro a un'organizzazione o che una fleet è stata eliminata correttamente, oltre a vedere altre azioni di gestione dello storage eseguite dagli utenti nella tua organizzazione.

I registri di controllo mostrano l'attività relativa ai seguenti servizi:

* Tenancy: azioni relative alla gestione della tua organizzazione, come aggiungere utenti, creare fleet e associare risorse.
* Gestione dello storage: azioni relative alla gestione delle risorse di storage.
* Federazione: azioni relative alla gestione delle federazioni, come la creazione di federazioni e l'aggiunta o la rimozione di organizzazioni federate.


.Passaggi
. Seleziona *Administration > Audit*.
. Utilizza i filtri sopra la tabella per modificare quali azioni vengono visualizzate nella tabella.
+
Ad esempio, puoi usare il filtro *Servizio* per mostrare le azioni relative a un servizio specifico, oppure puoi usare il filtro *Utente* per mostrare le azioni relative a un account utente specifico.





[[filter-audit-logs-for-identity-and-access-management-actions]]
=== Filtra i registri di controllo per azioni di gestione dell'identità e dell'accesso

Per visualizzare solo le azioni relative alla gestione della tua organizzazione, come l'aggiunta di membri, la creazione di flotte o l'eliminazione di risorse, filtra il registro di controllo in base al servizio Tenancy.

.Passaggi
. Seleziona *Administration > Audit*.
. Utilizza i filtri per restringere i risultati. Seleziona *Service* e poi *Tenancy*.
. Utilizza gli altri filtri per affinare ulteriormente i risultati.
+
Ad esempio, usa il filtro *Utente* per mostrare le azioni IAM eseguite da uno specifico account utente.





[[download-audit-logs-from-the-audit-page]]
=== Scarica i registri di controllo dalla pagina Audit

Puoi scaricare i log di audit dalla pagina Audit in un file CSV. Questo ti permette di tenere un registro delle azioni che gli utenti eseguono nella tua organizzazione. Il file CSV scaricato include tutte le colonne dei log di audit, indipendentemente dai filtri o dalle colonne visualizzate nella pagina Audit.

.Passaggi
. Nella pagina *Audit*, seleziona l'icona di download nell'angolo in alto a destra della tabella.

