= 
:allow-uri-read: 


Dopo aver installato e configurato l'agente della Console, aggiungi le tue credenziali cloud in modo che l'agente della Console disponga delle autorizzazioni necessarie per eseguire azioni in AWS o Azure.

[role="tabbed-block"]
====
.AWS
--
.Prima di iniziare
Se hai appena creato queste credenziali AWS, potrebbero essere necessari alcuni minuti prima che siano disponibili. Attendi qualche minuto prima di aggiungere le credenziali alla Console.

.Passaggi
. Seleziona *Amministrazione > Credenziali*.
. Seleziona *Credenziali dell'organizzazione*.
. Seleziona *Aggiungi credenziali* e segui i passaggi della procedura guidata.
+
.. *Posizione delle credenziali*: Seleziona *Amazon Web Services > Agent.
.. *Definisci le credenziali*: Inserisci una chiave di accesso AWS e una chiave segreta.
.. *Abbonamento al Marketplace*: associa un abbonamento al Marketplace a queste credenziali abbonandoti ora o selezionando un abbonamento esistente.
.. *Rivedi*: Conferma i dettagli relativi alle nuove credenziali e seleziona *Aggiungi*.




Ora puoi andare al https://console.netapp.com["NetApp Console"^] per iniziare a usare l'agente Console.

--
.Azure
--
.Prima di iniziare
Se hai appena creato queste credenziali Azure, potrebbero essere necessari alcuni minuti prima che siano disponibili. Attendi qualche minuto prima di aggiungere le credenziali all'agente della Console.

.Passaggi
. Seleziona *Amministrazione > Credenziali*.
. Seleziona *Aggiungi credenziali* e segui i passaggi della procedura guidata.
+
.. *Posizione delle credenziali*: Seleziona *Microsoft Azure > Agent*.
.. *Definisci le credenziali*: Inserisci le informazioni relative all'entità servizio Microsoft Entra che concede le autorizzazioni richieste:
+
*** ID applicazione (client)
*** ID directory (tenant)
*** Client Secret


.. *Abbonamento al Marketplace*: associa un abbonamento al Marketplace a queste credenziali abbonandoti ora o selezionando un abbonamento esistente.
.. *Rivedi*: Conferma i dettagli relativi alle nuove credenziali e seleziona *Aggiungi*.




.Risultato
L'agente della Console ora dispone delle autorizzazioni necessarie per eseguire azioni in Azure per tuo conto. Ora puoi andare alla https://console.netapp.com["NetApp Console"^] per iniziare a usare l'agente della Console.

--
====