= 
:allow-uri-read: 


Crea un ruolo e applicalo a un account di servizio che userai per l'istanza della VM agent della Console.

.Passaggi
. Crea un ruolo personalizzato in Google Cloud:
+
.. Crea un file YAML che includa le autorizzazioni definite nel link:reference-permissions-gcp.html["Criterio dell'agente della console per Google Cloud"].
.. Da Google Cloud, attiva cloud shell.
.. Carica il file YAML che include le autorizzazioni necessarie per l'agente della Console.
.. Crea un ruolo personalizzato usando il comando  `gcloud iam roles create`.
+
L'esempio seguente crea un ruolo denominato "connector" a livello di progetto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud docs: Creazione e gestione di ruoli personalizzati"^]



. Crea un account di servizio in Google Cloud:
+
.. Dal servizio IAM e amministrazione, seleziona *Account di servizio > Crea account di servizio*.
.. Inserisci i dettagli dell'account di servizio e seleziona *Crea e continua*.
.. Seleziona il ruolo che hai appena creato.
.. Completa i passaggi rimanenti per creare il ruolo.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud docs: Creazione di un account di servizio"^]





.Risultato
Ora disponi di un account di servizio che puoi assegnare all'istanza di agente Console.
