= 
:allow-uri-read: 


.Prima di iniziare
Dovresti avere quanto segue:

* Privilegi di root per installare l'agente della Console.
* Dettagli su un proxy server, se è necessario un proxy per l'accesso a Internet dall'agente della Console.
+
Puoi configurare un proxy server dopo l'installazione, ma per farlo devi riavviare l'agente della Console.

* Un certificato firmato da una CA, se il proxy server utilizza HTTPS o se il proxy è un proxy di intercettazione.



NOTE: Non puoi impostare un certificato per un proxy server trasparente quando installi manualmente l'agente della Console. Se hai bisogno di impostare un certificato per un proxy server trasparente, devi usare la Maintenance Console dopo l'installazione. Scopri di più sul link:reference-agent-maint-console.html["Console di manutenzione agente"].

.Informazioni su questa attività
Il programma di installazione disponibile sul NetApp Support Site potrebbe essere una versione precedente. Dopo l'installazione, l'agente della Console si aggiorna automaticamente se è disponibile una nuova versione.

.Passaggi
. Se le variabili di sistema _http_proxy_ o _https_proxy_ sono impostate sull'host, rimuovile:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se non rimuovi queste variabili di sistema, l'installazione non andrà a buon fine.

. Scarica il software dell'agente Console da  https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sito di supporto NetApp"^] e poi copialo sull'host Linux.
+
Dovresti scaricare il programma di installazione dell'agente "online" pensato per l'uso nella tua rete o nel cloud.

. Assegna le autorizzazioni per eseguire lo script.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Dove <version> è la versione dell'agente Console che hai scaricato.

. Esegui lo script di installazione.
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Dovrai aggiungere le informazioni sul proxy se la tua rete richiede un proxy per l'accesso a Internet. Puoi aggiungere un proxy trasparente o esplicito. I parametri --proxy e --cacert sono opzionali e non ti verrà richiesto di aggiungerli. Se hai un proxy server, dovrai inserire i parametri come mostrato.

+
Ecco un esempio di configurazione di un proxy server esplicito con un certificato firmato da una CA:

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configura l'agente Console per utilizzare un proxy server utilizzando uno dei seguenti formati:

+
** \http://indirizzo:porta
** http://nomeutente:password@indirizzo:port
** \http://nome-dominio%92nome-utente:password@indirizzo:porta
** https://address:port
** https://nomeutente:password@indirizzo:port
** \https://nome-dominio%92nome-utente:password@indirizzo:porta
+
Nota quanto segue:

+
*** L'utente può essere un utente locale o un utente di dominio.
*** Per un utente di dominio, devi usare il codice ASCII per una \ come mostrato sopra.
*** L'agente Console non supporta nomi utente o password che includono il carattere @.
*** Se la password include uno qualsiasi dei seguenti caratteri speciali, devi anteporre una barra rovesciata a quel carattere speciale: & o !
+
Per esempio:

+
\http://bxpproxyuser:netapp1\!@address:3128

+
--cacert specifica un certificato firmato da una CA da utilizzare per l'accesso HTTPS tra l'agente della Console e il proxy server. Questo parametro è richiesto per proxy server HTTPS, proxy server di intercettazione e proxy server trasparenti.



+
Ecco un esempio di configurazione di un proxy server trasparente. Quando configuri un proxy trasparente, non devi definire il proxy server. Devi solo aggiungere un certificato firmato da una CA all'host dell'agente della Console:



+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0 --cacert /tmp/cacert/certificate.cer
----
. Se hai utilizzato Podman, dovrai modificare la porta aardvark-dns.
+
.. Connettiti tramite SSH alla macchina virtuale dell'agente della Console.
.. Apri il file _/usr/share/containers/containers.conf_ di Podman e modifica la porta scelta per il servizio DNS Aardvark. Ad esempio, cambiala in 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Riavvia la macchina virtuale dell'agente della Console.




. Attendi il completamento dell'installazione.
+
Al termine dell'installazione, il servizio dell'agente della Console (occm) si riavvia due volte se hai specificato un proxy server.

. Apri un browser web da un host connesso alla macchina virtuale dell'agente della Console e inserisci il seguente URL:
+
https://_ipaddress_[]

. Dopo aver effettuato l'accesso, configura l'agente della Console:
+
.. Specifica l'organizzazione da associare all'agente della NetApp Console.
.. Inserisci un nome per il sistema.
.. Nella sezione *Stai eseguendo in un ambiente protetto?* lascia la modalità con restrizioni disattivata.
+
Dovresti mantenere la modalità limitata disabilitata perché questi passaggi spiegano come usare la Console in modalità standard. Dovresti abilitare la modalità limitata solo se hai un ambiente sicuro e vuoi disconnettere questo account dai servizi di backend. Se è così, link:task-quick-start-restricted-mode.html["Segui i passaggi per iniziare a utilizzare la NetApp Console in modalità limitata"].

.. Seleziona *Iniziamo*.



